version: '3'

services:
    app:
        build: ./docker/php
        volumes:
            - ./api:/var/www
        depends_on:
            - db
            - smtp4dev

    web:
        image: nginx
        ports:
            - 18080:80
        volumes:
            - ./api:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    node:
        build: ./docker/node
        ports:
            - '8090:8080'
        volumes:
            - ./client:/var/www
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myapp
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - 13306:3306
    smtp4dev:
        image: rnwood/smtp4dev:linux-amd64-v3
        ports:
            - '3000:80'